// <auto-generated />
using System;
using Invoice.API.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InvoiceAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20220529210234_AddInvoiceDataTableOnDB")]
    partial class AddInvoiceDataTableOnDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Invoice.API.Model.InvoiceEntity", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("FinalDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("final_date");

                    b.Property<DateTime>("InitialDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("initial_date");

                    b.Property<double>("Value")
                        .HasColumnType("double")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("invoice");
                });
#pragma warning restore 612, 618
        }
    }
}
